export const COMPONENT_REACT = "pricingReact";
export const COMPONENT_HTML = "pricingHtml";

export const PRODUCT_TYPES = ["component", "template"];

export const COMPONENT_LIST = [
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample1.png",
    hoverText: "This element displays several cost comparison.",
    title: "Pricing Sections",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-05-01",
    slug: "sample-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      title: "Pricing Sample 1",
      componentReact: "pricingReact",
      componentHTML: "pricingHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample2.png",
    hoverText: "On hover, the icons in this pricing component will change.",
    title: "Comparing Prices",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-08-23",
    slug: "sample-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Pricing Sample 2",
      componentReact: "pricingReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample3.png",
    hoverText: "This price includes wonderful distribution with promotion.",
    title: "Promotional Pricing",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2022-03-20",
    slug: "sample-3",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      title: "Pricing Sample 3",
      componentReact: "pricingReact",
      componentHTML: "pricingHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample4.png",
    hoverText: "This pricing component includes a free trial period.",
    title: "Pricing Plans",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-03-20",
    slug: "sample-4",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      title: "Pricing Sample 4",
      componentReact: "pricingReact",
      componentHTML: "pricingHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample5.png",
    hoverText:
      "The distribution of three pricing comparison is shown here in table style.",
    title: "Pricing Table",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-01-22",
    slug: "sample-5",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Pricing Sample 5",
      componentReact: "pricingReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcreditcard1.png",
    hoverText: "Component for credit cards that has dynamic colors and fields.",
    title: "Dynamic card",
    subTitle: "Creditcard component",
    type: "creditcard",
    date: "2023-01-01",
    slug: "card-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Creditcard sample 1",
      componentReact: "creditcardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcreditcard2.png",
    hoverText:
      "Beautiful graphic backdrop and field validation on the ATM card.",
    title: "Credit Card",
    subTitle: "Creditcard component",
    type: "creditcard",
    date: "2022-11-03",
    slug: "card-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Creditcard sample 2",
      componentReact: "creditcardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcreditcard3.png",
    hoverText: "ATM card with gorgeous graphic backdrop and field validation.",
    title: "Credit Card",
    subTitle: "Creditcard component",
    type: "creditcard",
    date: "2023-03-01",
    slug: "card-3",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Creditcard sample 3",
      componentReact: "creditcardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcarousal1.png",
    hoverText: "Responsive and simple carousel with arrows.",
    title: "Carousel with controls",
    subTitle: "Carousel component",
    type: "carousal",
    date: "2022-07-01",
    slug: "carousal-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Carousel sample 1",
      componentReact: "carousalReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcarousal2.png",
    hoverText:
      "Carousel component with an infinite loop, dynamic text, and with fade animation",
    title: "All-inclusive carousel",
    subTitle: "Carousel component",
    type: "carousal",
    date: "2023-03-20",
    slug: "carousal-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Carousel sample 2",
      componentReact: "carousalReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bg-cards.png",
    hoverText: "Attractive, functional, and effective card Layout.",
    title: "cards with scale effect",
    subTitle: "Card component",
    type: "card",
    date: "2023-03-01",
    slug: "profilecard",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Card sample 1",
      componentReact: "cardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/animation.gif",
    hoverText: "Component for the loader, button, and design with animation.",
    title: "Infinite Animation",
    subTitle: "Animation component",
    type: "animation",
    date: "2023-03-14",
    slug: "animation-infinite",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Animation Infinite",
      componentReact: "animationReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bg-btn-1.png",
    hoverText: "Flexible color and style buttons.",
    title: "categories of buttons",
    subTitle: "Button component",
    type: "button",
    date: "2023-03-16",
    slug: "sample1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Button",
      componentReact: "ButtonSampleReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bg-btn-2.png",
    hoverText:
      "Colorful buttons component with an outline,rounded and fill style.",
    title: "Fill and Round Buttons",
    subTitle: "Button component",
    type: "button",
    date: "2023-03-20",
    slug: "sample2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Button",
      componentReact: "ButtonSampleReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bganimatedbutton.gif",
    hoverText: "Components of buttons with different hover effects.",
    title: "3D Buttons",
    subTitle: "Button component",
    type: "button",
    date: "2023-03-13",
    slug: "sample3",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Button",
      componentReact: "ButtonSampleReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bginput.jpg",
    hoverText: "Various input field types with dynamic border colors.",
    title: "various inputs",
    subTitle: "Input component",
    type: "input",
    date: "2023-03-26",
    slug: "input-sample-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Input",
      componentReact: "inputReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgradiobutton.jpg",
    hoverText: "Radio button with a unique style.",
    title: "Radio Buttons.",
    subTitle: "Radio Button Component",
    type: "radiobutton",
    date: "2023-03-27",
    slug: "radiobutton-sample-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Radio Button",
      componentReact: "radioButtonReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcheckbox.png",
    hoverText: "Checkbox elements with vibrant and stylish categories.",
    title: "Checkbox Variations",
    subTitle: "Checkbox component",
    type: "checkbox",
    date: "2023-03-28",
    slug: "checkbox-sample-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Check Box",
      componentReact: "checkboxReact",
    },
  },

  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgadvertise.png",
    hoverText: "Advertise components that highlight important points.",
    title: "Advertise card",
    subTitle: "Card component",
    type: "card",
    date: "2023-04-06",
    slug: "advertise",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Advertise Card",
      componentReact: "cardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown1.png",
    hoverText: "Timer component to show the user how much time has to wait.",
    title: "Day Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-07",
    slug: "timer-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Timer Component 1",
      componentReact: "timerReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown2.png",
    hoverText:
      "A responsive timer that displays the conclusion of our waiting time.",
    title: "Box Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-10",
    slug: "timer-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Timer Component 2",
      componentReact: "timerReact",
    },
  },

  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown3.png",
    hoverText:
      "Timer component which used to display remaining time for a particular function.",
    title: "Countdown Labels",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-01",
    slug: "timer-3",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Timer Component 3",
      componentReact: "timerReact",
    },
  },

  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown4.png",
    hoverText:
      "A responsive timer that displays the conclusion of our waiting time.",
    title: "Live Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-05",
    slug: "timer-4",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Timer Component 4",
      componentReact: "timerReact",
    },
  },

  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown5.png",
    hoverText:
      "Timer component which used to display remaining time for a particular function.",
    title: "Circle Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-09",
    slug: "timer-5",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Timer Component 5",
      componentReact: "timerReact",
    },
  },
];
