export const TemplateConstant = [
  {
    mainImageSrc: "/bgcomponents/bgnft.png",
    hoverText: "This is Landing Page Template",
    title: "3DNFT",
    subTitle: "Landing Page 1",
    type: "3dnft",
    date: "2023-09-11",
    slug: "temp1",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "3DNFT",
      componentReact: "templateReact",
    },
  },
  {
    mainImageSrc: "/bgcomponents/bgcrypto.png",
    hoverText: "This is Landing Page Template",
    title: "Crypto",
    subTitle: "Landing Page 2",
    type: "crypto",
    date: "2023-01-09",
    slug: "temp2",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Crypto",
      componentReact: "templateReact",
    },
  },
  {
    mainImageSrc: "/bgcomponents/bgadvocate.png",
    hoverText: "This is Landing Page Template",
    title: "Advocate",
    subTitle: "Landing Page 3",
    type: "advocate",
    date: "2023-05-01",
    slug: "temp3",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "Advocate",
      componentReact: "templateReact",
    },
  },
  {
    mainImageSrc: "/bgcomponents/bgtbdesign.png",
    hoverText: "This is Landing Page Template",
    title: "TBDesign",
    subTitle: "Landing Page 4",
    type: "tbdesign",
    date: "2023-05-01",
    slug: "temp4",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      title: "TBDesign",
      componentReact: "templateReact",
    },
  },
];
